# Generated by Django 2.0.2 on 2018-02-23 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
