# Generated by Django 2.0.2 on 2018-02-24 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180224_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='bid',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='uid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='wish',
            field=models.ManyToManyField(blank=True, related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
